
version: '3'

services:

    mosquitto:
        image:                  eclipse-mosquitto:latest
        hostname:               mosquitto
        container_name:         mosquitto
        
        volumes:
        -                     ./broker/mosquitto/config:/mosquitto/config
        -                     ./broker/mosquitto/certs:/mosquitto/certs
        networks:
        -                     backend-network 
        expose:
        -                     "8883"
        ports:
        -                     "8883:8883"

networks:
    backend-network:
        driver:                 bridge