
version: '3'

services:

    mosquitto:
        image:                  eclipse-mosquitto:latest
        hostname:               mosquitto
        container_name:         mosquitto
        
        volumes:
        -                     ./broker/mosquitto/config:/mosquitto/config
        -                     ./broker/mosquitto/certs:/mosquitto/certs
        networks:
        -                     backend-network 
        expose:
        -                     "8883"
        ports:
        -                     "8883:8883"

    db:
        image:                  mongo:latest
        hostname:               mongodb
        container_name:         mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: iot
        ports:
            -                   "27017:27017"
        expose:
            -                   "27017"
        volumes:
            -                   ./db/dump/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            -                   ./db/data:/data/db
        networks:
            -                     backend-network 

    api:
        image:                  node:14
        hostname:               api
        container_name:         api
        volumes:
            -                   ./api:/home/src
        environment: 
            NODE_PATH:          /home/node_modules
        working_dir:            /home/src
        command:                sh -c "npm install -g && 
                                        node index.js"
        depends_on:
            -                    db                                
        ports: 
            -                   3000:3000
        networks:
            -                   backend-network 

    core:
        image:                  node:14
        hostname:               core
        container_name:         core
        volumes:
            -                   ./core:/home/src
        environment: 
            NODE_PATH:          /home/node_modules
        working_dir:            /home/src
        command:                sh -c "npm install -g && 
                                        node index.js"
        depends_on:
            -                    db
            -                    api
            -                    mosquitto                                
        ports: 
            -                   3001:3001
        networks:
            -                   backend-network 

networks:
    backend-network:
        driver:                 bridge